### PR TITLE
Fix for too many open files issue on 22.04

### PR DESCRIPTION
**Pull request by pritambhat001**
This fix is for ulimit of files and resources while deploying AMP on ubuntu 22.04.

### CODE REVIEW

**Comment by llpeterson** [comment]
This needs some work. First, it shouldn't be specific to installing AMP. It's dependent on the order in which charts are deployed. SD-Core before AMP likely causes AMP to fail. AMP before SD-Core likely causes SD-Core to fail. (I would also be fine with it not being tied to 22.04, but instead include it as a standard configuration for whatever version of Ubuntu is installed.) Second, it should be implemented as an Ansible playbook. I would very much like to avoid special case Makefile rules. Third, and this is a question I have about the details... the PR both sets the file limits in sysctl.conf, and sets other variables in /etc/pam.d/common-session and /etc/security/limits.conf. Those don't appear strictly related to the open file limit. Are those other config variations you've had to address?

**Comment by llpeterson** [comment]
Hussain (on the onramp channel) says the following appended to the end of sysctl.conf is sufficient:

fs.file-max=2097152
fs.inotify.max_user_watches=524288
fs.inotify.max_user_instances=512

I plan to give a try on both 20.04 and 22.04.

**Comment by pritambhat001** [comment]
@llpeterson I have tried the aether-onramp deployment and  gnbsim test by adding below lines in sysctl.conf file on both 20.04 and 22.04. On both versions of ubuntu it is working fine without any error.

fs.file-max=2097152
fs.inotify.max_user_watches=524288
fs.inotify.max_user_instances=512

**Comment by llpeterson** [comment]
Thanks. Let me chat with BIlal about the right way to integrate this change.

**Pull request closed without merging**
